### ISSUE TITLE
Data source incomplete

### ISSUE THREAD

**Issue by joshpeng** [roblourens/vscode-stocks#1]
The current data source doesn't have many common instruments. For example SPY (S&P500 ETF) or QQQ (Nasdaq ETF) aren't available.

Ex: The API call for SPY yields APP_SPECIFIC_ERROR instead of a price http://dev.markitondemand.com/MODApis/Api/v2/Quote/jsonp?symbol=SPY&callback=myFunction

Furthermore, I don't think the prices are updating. AAPL shows last Friday's price instead of an actual updated price from today.
http://dev.markitondemand.com/MODApis/Api/v2/Quote/jsonp?symbol=aapl&callback=myFunction it says the date is 10/21, but markets are already open for 10/24. This might be an end-of-day market data source instead of real-time.

**Comment by roblourens** [comment]
You're right, there's probably a better data source out there. I couldn't notice that over the weekend :)

**Comment by joshpeng** [comment]
Seems like the Yahoo Finance API is no longer working without some weird [user agent hack](http://stackoverflow.com/questions/38355075/has-yahoo-finance-web-service-disappeared-api-changed-down-temporarily/38454315#38454315).
Prob alright to just use Google's instead since we don't have any real data speed/fidelity requirements here for this extension. [https://www.google.com/finance/info?q=msft, aapl](https://www.google.com/finance/info?q=msft, aapl)

**Comment by roblourens** [comment]
I thought theirs was deprecated - https://developers.google.com/finance/ - but, there it is... thanks for pointing that out.

**Comment by roblourens** [comment]
Done in 0.0.3, thanks again for the tip

**Comment by joshpeng** [comment]
Seems their deprecation process finished.
Data no longer available at that endpoint :[

**Comment by roblourens** [comment]
Noticed that :(
Do you know a better one?

**Comment by joshpeng** [comment]
This Yahoo one seems to work. Not sure about if it gets real-time updates or not at the moment since markets are closed. https://support.klipfolio.com/hc/en-us/articles/215546368-Use-Yahoo-Finance-as-a-data-source-
